# Generated by Django 6.0.1 on 2026-01-17 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUP', 'SuperAdmin'), ('ADM', 'Admin'), ('User', 'User')], max_length=4)),
                ('name', models.CharField()),
                ('mobileNumber', models.CharField(blank=True, null=True)),
                ('gmail', models.CharField()),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('profile', models.FileField(blank=True, null=True, upload_to='users/profile/')),
                ('is_login', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_logout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefered_language_for_dailyWord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyword_users', to='languages.languagelist')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='appusers.appuser')),
            ],
        ),
    ]
