# Generated by Django 6.0.1 on 2026-01-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongLyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_no', models.IntegerField(unique=True)),
                ('song_name', models.CharField(max_length=200)),
                ('song_title', models.TextField()),
                ('priseWord', models.TextField()),
                ('song_lyric', models.TextField()),
                ('song_audio', models.FileField(blank=True, null=True, upload_to='songs/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
