# Generated by Django 6.0.1 on 2026-01-17 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testament', models.CharField(choices=[('OT', 'Old Testament - 39'), ('NT', 'New Testment - 27')], default='OT', max_length=2)),
                ('booknumber', models.PositiveIntegerField()),
                ('bookName', models.CharField(max_length=100)),
                ('chapters', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bibleLanguage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bible_books', to='languages.languagelist')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_chapter', models.PositiveIntegerField()),
                ('no_of_verses', models.PositiveIntegerField()),
                ('verses', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_verses', to='bible.biblebook')),
            ],
        ),
    ]
